# Generated by Django 5.0.6 on 2026-04-08 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('full_exam', 'Full Exam')], default='practice', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('total_score', models.IntegerField(null=True)),
                ('max_score', models.IntegerField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('part_scores', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_responses',
            },
        ),
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.JSONField(default=list)),
                ('mark_status', models.CharField(choices=[('pending', 'Pending'), ('marking', 'Marking'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score_grammar', models.IntegerField(null=True)),
                ('score_discourse', models.IntegerField(null=True)),
                ('score_interaction', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('band', models.CharField(blank=True, default='', max_length=1)),
                ('cefr', models.CharField(blank=True, default='', max_length=10)),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('suggestion', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speaking_responses',
            },
        ),
        migrations.CreateModel(
            name='WritingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('mark_status', models.CharField(choices=[('pending', 'Pending'), ('marking', 'Marking'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score_content', models.IntegerField(null=True)),
                ('score_communicative', models.IntegerField(null=True)),
                ('score_organisation', models.IntegerField(null=True)),
                ('score_language', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('band', models.CharField(blank=True, default='', max_length=1)),
                ('cefr', models.CharField(blank=True, default='', max_length=10)),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('suggestion', models.TextField(blank=True, default='')),
                ('zero_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writing_responses',
            },
        ),
    ]
