# Generated by Django 5.0.6 on 2026-04-08 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('time_mins', models.IntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.CharField(choices=[('1', 'Part 1 - Interview'), ('2', 'Part 2 - Long Turn'), ('3', 'Part 3 - Collaborative'), ('4', 'Part 4 - Discussion')], max_length=1)),
                ('label', models.CharField(max_length=200)),
                ('instruction', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('questions', models.JSONField(default=list)),
                ('situation_a', models.TextField(blank=True, default='')),
                ('situation_b', models.TextField(blank=True, default='')),
                ('central_question', models.TextField(blank=True, default='')),
                ('options', models.JSONField(default=list)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_parts', to='exams.exam')),
            ],
            options={
                'db_table': 'speaking_parts',
                'ordering': ['order', 'part'],
            },
        ),
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2')], default=1)),
                ('question_type', models.CharField(choices=[('email', 'Email'), ('article', 'Article'), ('story', 'Story'), ('picture', 'Picture')], default='email', max_length=20)),
                ('label', models.CharField(default='Question 1', max_length=100)),
                ('instruction', models.TextField(blank=True, default='')),
                ('write_instruction', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('email_from', models.CharField(blank=True, default='', max_length=200)),
                ('email_subject', models.CharField(blank=True, default='', max_length=300)),
                ('email_body', models.TextField(blank=True, default='')),
                ('notes', models.JSONField(default=list)),
                ('prompt_title', models.CharField(blank=True, default='', max_length=300)),
                ('prompt_heading', models.CharField(blank=True, default='', max_length=300)),
                ('prompt_items', models.JSONField(default=list)),
                ('story_opener', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'db_table': 'writing_questions',
                'ordering': ['order', 'part'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.IntegerField(choices=[(1, 'Multiple Choice - Signs & Notices'), (2, 'Matching'), (3, 'True / False'), (4, 'Multiple Choice - Article'), (5, 'Multiple Choice Cloze'), (6, 'Open Cloze')])),
                ('has_content', models.BooleanField(default=False)),
                ('content', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_parts', to='exams.exam')),
            ],
            options={
                'db_table': 'reading_parts',
                'ordering': ['part_number'],
                'unique_together': {('exam', 'part_number')},
            },
        ),
    ]
