# Generated by Django 5.0.6 on 2026-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_exam_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
